
layout: page
titlse: Notes
permalink: ./index.md
theme: jekyll-theme-minimal
author: Piyush
description: >-
  Learn how to create a site or blog from your GitHub repositories with GitHub
  Pages.
markdown: kramdown

